apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- files:
  - ddi-realm.json
  name: ddi-realm
  behavior: merge
- files:
  - theme.css
  name: login-theme
  behavior: merge
- name: environment
  files:
    - values.yaml=values.yaml
  behavior: merge
generatorOptions:
  disableNameSuffixHash: true
